insert into contacts (first_name, last_name, email, phone, company, notes,
                      street, city, state, postal_code, country, created_at, updated_at)
values
  ('Ada', 'Lovelace', 'ada.lovelace@example.com', '+1-555-0100', 'Analytical Engines Ltd',
   'First programmer. Prefers email.',
   '12 Marylebone Rd', 'London', null, 'NW1 5LA', 'UK', current_timestamp, current_timestamp),
  ('Grace', 'Hopper', 'grace.hopper@example.com', '+1-555-0101', 'US Navy',
   'Coined the term debugging.',
   '1 Navy Yard', 'Arlington', 'VA', '22202', 'USA', current_timestamp, current_timestamp),
  ('Alan', 'Turing', 'alan.turing@example.com', '+44-555-0102', 'Bletchley Park', null,
   'The Mansion', 'Milton Keynes', null, 'MK3 6EB', 'UK', current_timestamp, current_timestamp),
  ('Katherine', 'Johnson', 'katherine.johnson@example.com', '+1-555-0103', 'NASA',
   'Orbital mechanics.',
   '21000 Brookpark Rd', 'Cleveland', 'OH', '44135', 'USA', current_timestamp, current_timestamp),
  ('Barbara', 'Liskov', 'barbara.liskov@example.com', '+1-555-0104', 'MIT',
   'Substitution principle.',
   '77 Massachusetts Ave', 'Cambridge', 'MA', '02139', 'USA', current_timestamp, current_timestamp),
  ('Margaret', 'Hamilton', 'margaret.hamilton@example.com', '+1-555-0105', 'MIT Instrumentation Lab',
   'Apollo guidance software.',
   '1 Hampshire St', 'Cambridge', 'MA', '02139', 'USA', current_timestamp, current_timestamp),
  ('Linus', 'Torvalds', 'linus.torvalds@example.com', '+1-555-0106', 'Linux Foundation', null,
   '548 Market St', 'San Francisco', 'CA', '94104', 'USA', current_timestamp, current_timestamp),
  ('Radia', 'Perlman', 'radia.perlman@example.com', '+1-555-0107', 'Dell EMC',
   'Spanning tree protocol.',
   '176 South St', 'Hopkinton', 'MA', '01748', 'USA', current_timestamp, current_timestamp),
  ('Anita', 'Borg', 'anita.borg@example.com', null, 'Institute for Women and Technology', null,
   null, 'Palo Alto', 'CA', '94301', 'USA', current_timestamp, current_timestamp),
  ('Tim', 'Berners-Lee', 'tim.berners-lee@example.com', '+41-555-0108', 'W3C',
   'Invented the web.',
   'Rue de Meyrin', 'Geneva', null, '1211', 'CH', current_timestamp, current_timestamp);
